openapi: 3.0.0
info:
  title: Pokédex
  description: Endpoints available for the Pokédex API
  version: '1.0'
servers:
  - url:  'http://localhost:8080/api'


paths: 
  /v1/pokedex: 
    get: 
      tags:
        - Get all
      summary: List all pokémons from the Pokédex
                
      responses:
        '200':
          description: pokémons retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pokedexPokemons'
        '400':
          description: bad request.
    post:
      tags:
        - Add pokémon 
      summary: Add new pokémon to Pokédex
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pokemonId:
                  type: string
                  example: 1
                  description: id of pokémon to add to Pokédex
      responses:
        '201':
          description: pokémon added to Pokédex.
        '400':
          description: bad request.
        '422':
          description: pokémon already in the Pokédex.
        '404':
          description: pokémon not found by id.
    delete:
      tags:
        - Delete all 
      summary: Delete all pokémons from Pokédex
      responses:
        '200':
          description: all pokémons deleted from the Pokédex.
        '400':
          description: bad request.
          
  /v1/pokedex/{pokemonId}:
    get:
      tags: 
        - Get pokémon by id
      summary: Get a Pokédex pokémon by its id
      parameters:
        - name: pokemonId
          in: path
          description: pokémon id
          required: true
          schema:
            type: integer
      
      responses:
        '200':
          description: pokémon retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pokedexPokemon'
        '400':
          description: bad request.
        '404':
          description: pokémon not found by id.
    delete:
      tags:
        - Delete pokémon by id
      summary: Delete a pokémon from the Pokédex by its id
      parameters:
        - name: pokemonId
          in: path
          description: pokémon id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: pokémon deleted
        '400':
          description: bad request.
        '404':
          description: pokémon not found by id.
    
components:
  schemas:
    pokedexPokemon:
      type: object
      properties:
        id:
          type: object
          properties:
            timestamp:
              example: 1692198155
              description: time stamp
            date:
              example: "2023-08-16T15:02:35.000+00:00"
              description: date
        pokemonId:
          type: integer
          example: 2
          description: pokémon id
        abilities:
          type: array
          items:
            type: object
            properties:
              ability: 
                type: object
                properties:
                  name: 
                    type: string
                    example: "overgrow"
                    description: ability
          description: list of abilities
        height:
          type:  integer
          example: 10
          description: height
        name:
          type: string
          example: 'ivysaur'
          description: pokémon name
        weight:
          type: integer
          example: 130
          description: weight
        types:
          type: array
          items:
            type: object
            properties:
              type:
                type: object
                properties:
                  name:
                    type: string
                    example: "grass"
                    description: type
        sprites:
          type: object
          properties:
            other:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    front_default:
                      type: string
                      example: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png"
                      description: icon link
        nickname:
          type: string
          example: "Green"
          description: nickname
    pokedexPokemons:
      type: array
      items:
        $ref: '#/components/schemas/pokedexPokemon'
            
          
          
          
          
