openapi: 3.0.0
info:
  title: Starred Pokémons
  description: Endpoints available for the Starred Pokémons API
  version: '1.0'
servers:
  - url:  'http://localhost:8080/api'


paths: 
  /v1/starred: 
    get: 
      tags:
        - Get all
      summary: List all starred pokémons 
                  
      responses:
        '200':
          description: starred pokémons retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/starredPokemons'
        '400':
          description: bad request.
    
    post:
      tags:
        - Add starred pokémon
      summary: Add a pokémon to starred pokémons
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pokemonId:
                  type: integer
                  example: 1
                  description: id of pokémon to add to starred
                nickname:
                  type: string
                  example: Red
                  description: nickname of pokémon to add to starred
      responses:
        '201':
          description: pokémon added to starred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/starredPokemon'
        '400':
          description: bad request.
        '422':
          description: pokémon already in the starred collection.
        '404':
          description: pokémon not found by id.
    
    delete:
      tags:
        - Delete all 
      summary: Delete all pokémons from starred pokémons
      responses:
        '200':
          description: all pokémons deleted from starred pokémons.
        '400':
          description: bad request.
          
    patch:
      tags:
        - Edit nickname
      summary: Edit nickname of starred pokémon
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pokemonId:
                  type: integer
                  example: 1
                  description: id of pokémon to edit
                nickname:
                  type: string
                  example: Red
                  description: nickname of pokémon to edit
      responses:
        '200':
            description: pokémon nickname edited.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/starredPokemon'
        '400':
          description: bad request.
        '404':
          description: starred pokémon not found by id.
      
          
  /v1/starred/{pokemonId}:
    get:
      tags: 
        - Get starred pokémon
      summary: Get a starred pokémon by its id
      parameters:
        - name: pokemonId
          in: path
          description: pokémon id
          required: true
          schema:
            type: integer
      
      responses:
        '200':
          description: starred pokémon retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/starredPokemon'
        '400':
          description: bad request.
        '404':
          description: starred pokémon not found by id.
          
    delete:
      tags:
        - Delete starred pokémon
      summary: Delete a pokémon from the starred pokémons by its id
      parameters:
        - name: pokemonId
          in: path
          description: pokémon id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: pokémon deleted from starred pokémons.
        '400':
          description: bad request.
        '404':
          description: starred pokémon not found by id.
          
    
components:
  schemas:
    starredPokemon:
      type: object
      properties:
        id:
          type: object
          properties:
            timestamp:
              example: 1692198155
              description: time stamp
            date:
              example: "2023-08-16T15:02:35.000+00:00"
              description: date
        pokemonId:
          type: integer
          example: 2
          description: pokémon id
        abilities:
          type: array
          items:
            type: object
            properties:
              ability: 
                type: object
                properties:
                  name: 
                    type: string
                    example: "overgrow"
                    description: ability
          description: list of abilities
        height:
          type:  integer
          example: 10
          description: height
        name:
          type: string
          example: 'ivysaur'
          description: pokémon name
        weight:
          type: integer
          example: 130
          description: weight
        types:
          type: array
          items:
            type: object
            properties:
              type:
                type: object
                properties:
                  name:
                    type: string
                    example: "grass"
                    description: type
        sprites:
          type: object
          properties:
            other:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    front_default:
                      type: string
                      example: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png"
                      description: icon link
    starredPokemons:
      type: array
      items:
        $ref: '#/components/schemas/starredPokemon'
            
          
          
          
          
